import "server-only";

export const serverEnv = {
  NODE_ENV: process.env.NODE_ENV ?? "development",
  PORT: Number(process.env.PORT ?? 3000),
  VERCEL_URL: process.env.VERCEL_URL ?? "",
  SKIP_ENV_VALIDATION: Boolean(process.env.SKIP_ENV_VALIDATION),
  USE_DEBUG_LOGS: Boolean(process.env.USE_DEBUG_LOGS),
  BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET ?? "",
  BETTER_AUTH_URL: process.env.BETTER_AUTH_URL ?? "",
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID ?? "",
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET ?? "",
  RESEND_API_KEY: process.env.RESEND_API_KEY ?? "",
  RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL ?? "",
  VERCEL: Number(process.env.VERCEL ?? 0),
  DATABASE_URL: process.env.DATABASE_URL ?? "",
  ARKJET_API_KEY: process.env.ARKJET_API_KEY ?? "",
  BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN ?? "",
  AI_PROVIDER: process.env.AI_PROVIDER ?? "ollama",
  OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL ?? "http://127.0.0.1:11434/api",
  OLLAMA_MODEL: process.env.OLLAMA_MODEL ?? "qwen3.5:0.8b",
  STARTER_CREDITS: Number(process.env.STARTER_CREDITS ?? 50000),
  CHAT_RESERVE_MIN_CREDITS: Number(process.env.CHAT_RESERVE_MIN_CREDITS ?? 256),
  CHAT_RESERVE_RATIO: Number(process.env.CHAT_RESERVE_RATIO ?? 2),
  SUBSCRIPTION_MONTHLY_CREDITS: Number(process.env.SUBSCRIPTION_MONTHLY_CREDITS ?? 250000),
  MAX_UPLOAD_FILE_SIZE_BYTES: Number(process.env.MAX_UPLOAD_FILE_SIZE_BYTES ?? 10485760),
  MAX_UPLOAD_FILES_PER_MESSAGE: Number(process.env.MAX_UPLOAD_FILES_PER_MESSAGE ?? 5),
  RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID ?? "",
  RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET ?? "",
  RAZORPAY_WEBHOOK_SECRET: process.env.RAZORPAY_WEBHOOK_SECRET ?? "",
  RAZORPAY_STARTER_PLAN_ID: process.env.RAZORPAY_STARTER_PLAN_ID ?? "",
  RAZORPAY_PRO_PLAN_ID: process.env.RAZORPAY_PRO_PLAN_ID ?? "",
  INNGEST_EVENT_KEY: process.env.INNGEST_EVENT_KEY ?? "",
  INNGEST_SIGNING_KEY: process.env.INNGEST_SIGNING_KEY ?? "",
};
